version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/config:/etc/prometheus
      #- ./prometheus/data:/prometheus
    ports:
      - "9999:9090"
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana/config:/etc/grafana
      #- ./grafana/data:/var/lib/grafana      
    ports:
      - "3333:3000"
    depends_on:
      - prometheus
